import { M_PLUS_1p, Montserrat } from "next/font/google";
import "./globals.css";

const mplus1p = M_PLUS_1p({
  weight: ["400", "500", "700", "800"],
  variable: "--font-m-plus-1p",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  weight: ["400", "500", "700", "800"],
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={`${mplus1p.variable} ${montserrat.variable}`}>
        {children}
      </body>
    </html>
  );
}
